version: "3"

volumes:
  database:
    driver: local

services:
  db:
    image: postgres:latest
    container_name: "purple-postgres"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql-docker/data

  # If you want to run the remix app also inside Docker
  #
  # ppt:
  #   environment:
  #     DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
  #   container_name: ppt
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 3000:3000
